### ISSUE TITLE
bmi 예측 모델 api화 하기

### ISSUE THREAD

**Issue by IT-HONGREAT** [IT-HONGREAT/django_food_project#33]
## What??

- bmi예측 ML모델과 그 기능을 restapi 화 하기

## Why??

- explore & study

## To-do List

- [x]  브랜치 생성
- [x]  기존 bmi 변경이 아닌 bmi_api app 생성
- [x]  구현(추가)

**Comment by IT-HONGREAT** [comment]
## 구현완료

* 계획변경 전
    * 이번 주말까지 구현하고 발생하는 에러들과 애로사항을 정리하려함
* 계획변경 후
    * operation 에러와 코드컨벤션에 대한 에러들이 많아서 금방금방 처리했더니 1시간30분만에 구현되버림..
    * 리팩토링 필요한 부분은 수정해야함

## BMI predict에 대해..

* restframework 로 구현된 bmi와 direct로 view단에서 구현된 bmi를 서로 다른 브랜치로 구분하여 지속할지?
* url로 크게 엮이지 않는다면 legacy로 유지할지? 고민! 
    * 브랜치 재분기 / issue_31 브랜치 (restapi)유지

## To-do List

- [ ]  코드리팩토링 필요한 부분에 대해서 탐구 및 코드 정리
- [ ]  과정 복기하면서 정리
- [ ]  오류사항 정리 및 탐구

## 예측값 잘 나오는 모습
<img width="688" alt="image" src="https://user-images.githubusercontent.com/80932397/153420158-1655a2bc-5d31-40f1-ac4b-07b18cc22178.png">
